=== Paez11/Lenguaje-de-marcas/1Trimestre/xml_xsd/examen/exam2.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="canales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="canal" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="programacion" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="titulo" type="xs:string"/>
                                                    <xs:element name="descripcion" type="xs:string"/>
                                                    <xs:element name="clasificacion_edad" type="xs:positiveInteger"/>
                                                    <xs:element name="subtitulos" minOccurs="0">
                                                        <xs:complexType>
                                                                <xs:attribute name="hay" type="xs:boolean" use="optional" default="0"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="idioma">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="seleccion"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="tipo" type="xs:string" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="anuncios" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="anuncio">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="marca" type="xs:string"/>
                                                                <xs:element name="durancion" type="xs:string"/>
                                                                <xs:element name="horario" type="xs:string" minOccurs="1" maxOccurs="3"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="numero" type="xs:positiveInteger" use="required"/>
                    </xs:complexType>  
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Paez11/Lenguaje-de-marcas/1Trimestre/xml_xsd/examen/exam2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE canales>

<canales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="exam2.xsd">
    <canal numero="1">
        <programacion>
            <dia tipo="lunes">
                <titulo> friends </titulo>
                <descripcion> va sobre amigos </descripcion>
                <clasificacion_edad> 7 </clasificacion_edad>
                <subtitulos hay="0"></subtitulos>
                <idioma>
                    <seleccion> espa√±ol </seleccion>
                </idioma>
            </dia>
            <dia tipo="martes">
                <titulo> the simpsons </titulo>
                <descripcion> va sobre una familia </descripcion>
                <clasificacion_edad> 7 </clasificacion_edad>
                <subtitulos hay="1"></subtitulos>
                <idioma>
                    <seleccion> ingles </seleccion>
                </idioma>
            </dia>
            <anuncios>
                <anuncio>
                    <marca> coca-cola </marca>
                    <durancion> 20 segundos </durancion>
                    <horario> 1 </horario>
                </anuncio>
            </anuncios>
            <anuncios>
                <anuncio>
                    <marca> audi </marca>
                    <durancion> 30 segundos </durancion>
                    <horario> 2 </horario>
                </anuncio>
            </anuncios>
            <anuncios>
                <anuncio>
                    <marca> warner bros </marca>
                    <durancion> 14 segundos </durancion>
                    <horario> 3 </horario>
                </anuncio>
            </anuncios>
        </programacion>
    </canal>
    
</canales>
